services:
  - type: web
    name: curser-stocker
    env: python
    buildCommand: pip install -r requirements-prod.txt
    startCommand: gunicorn wsgi:application --workers 4 --threads 2 --timeout 60 --worker-class gthread
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: HUGGINGFACE_API_KEY
        sync: false
    autoDeploy: true 